import img1 from '../assets/Img/10001.jpg'
import img2 from '../assets/Img/10002.jpg'
import img3 from '../assets/Img/10003.jpg'
import img4 from '../assets/Img/10004.jpg'
import img5 from '../assets/Img/10005.jpg'
import img6 from '../assets/Img/10006.jpg'
import img7 from '../assets/Img/10007.jpg'
import img8 from '../assets/Img/10008.jpg'
import img9 from '../assets/Img/10009.jpg'
import img10 from '../assets/Img/10010.jpg'
import img11 from '../assets/Img/10011.jpg'
import img12 from '../assets/Img/10012.jpg'
import img13 from '../assets/Img/10013.jpg'
import img14 from '../assets/Img/10014.jpg'
import img15 from '../assets/Img/10015.jpg'
import img16 from '../assets/Img/10016.jpg'
import img17 from '../assets/Img/10017.jpg'
import img18 from '../assets/Img/10018.jpg'
import img19 from '../assets/Img/10019.jpg'
import img20 from '../assets/Img/10020.jpg'
import img21 from '../assets/Img/10021.jpg'
import img22 from '../assets/Img/10022.jpg'
import img23 from '../assets/Img/10023.jpg'
import img24 from '../assets/Img/10024.jpg'
import img25 from '../assets/Img/10025.jpg'
import img26 from '../assets/Img/10026.jpg'
import img27 from '../assets/Img/10027.jpg'
import img28 from '../assets/Img/10028.jpg'
import img29 from '../assets/Img/10029.jpg'
import img30 from '../assets/Img/10030.jpg'
import img31 from '../assets/Img/10031.jpg'
import img32 from '../assets/Img/10032.jpg'
import img33 from '../assets/Img/10033.jpg'
import img34 from '../assets/Img/10034.jpg'
import img35 from '../assets/Img/10035.jpg'
import img36 from '../assets/Img/10036.jpg'
import img37 from '../assets/Img/10037.jpg'
import img38 from '../assets/Img/10038.jpg'
import img39 from '../assets/Img/10039.jpg'
import img40 from '../assets/Img/10040.jpg'
import img41 from '../assets/Img/10041.jpg'
import img42 from '../assets/Img/10042.jpg'
import img43 from '../assets/Img/10043.jpg'
import img44 from '../assets/Img/10044.jpg'
import img45 from '../assets/Img/10045.jpg'
import img46 from '../assets/Img/10046.jpg'
import img47 from '../assets/Img/10047.jpg'
import img48 from '../assets/Img/10048.jpg'
import img49 from '../assets/Img/10049.jpg'

export const pictaTeam = [
    {
        id: 0,
        type: 'product',
        img: img1,
        name: 'Guillaume',
        title: 'CEO/ CPO',
        otherInfoOne: 'I like jalapenos 🌶',
        otherInfoTwo: 'Prime rib - Burgundy wine ♥ 🍷',
        otherInfoThree: 'Conducting the Picta orchestra 🎻',
        otherInfoFour: 'I hate rainy weekends 🌧',
        otherInfoFive: '',
    },
    {
        id: 1,
        type: 'marketing',
        img: img2,
        name: 'Max',
        title: 'CMO',
        otherInfoOne: 'I like melted cheese 🧀',
        otherInfoTwo: 'I am a fan of tennis 🎾',
        otherInfoThree: 'I like coding in python 🐍',
        otherInfoFour: "I don't like finishing my...",
        otherInfoFive: '',
    },
    {
        id: 2,
        type: 'engineering',
        img: img3,
        name: 'François',
        title: 'CTO',
        otherInfoOne: 'I like sneakers 👟',
        otherInfoTwo: 'I am a LEGO fan 🧱',
        otherInfoThree: 'I raise devs and designers...',
        otherInfoFour: "I don't like eating healthy 🥦",
        otherInfoFive: '',
    },
    {
        id: 3,
        type: 'engineering',
        img: img4,
        name: 'Anthony',
        title: 'Engineering Manager Web',
        otherInfoOne: 'I like it spicy 🌶',
        otherInfoTwo: 'I love scuba diving 🤿',
        otherInfoThree: 'I am Swiss Army Knife 🧑‍🔧',
        otherInfoFour: 'I hate being bored 🥱',
        otherInfoFive: '',
    },
    {
        id: 4,
        type: 'product',
        img: img5,
        name: 'Quentin',
        title: 'PM Manager',
        otherInfoOne: 'I like photography 📸',
        otherInfoTwo: ' I am a muscian 🎸',
        otherInfoThree: ' I m a data- master 📊',
        otherInfoFour: 'I hate Twingos 🚗',
        otherInfoFive: '',
    },
    {
        id: 5,
        type: 'partnership',
        img: img6,
        name: 'Meghan',
        title: 'Partnership Manager',
        otherInfoOne: 'I like food/wine pairings 🍷',
        otherInfoTwo: 'I ♥ DIY YouTubers',
        otherInfoThree: 'I dream BIG! 🗻',
        otherInfoFour: 'I hate feeling hot 🥵',
        otherInfoFive: '',
    },
    {
        id: 6,
        type: 'people',
        img: img7,
        name: 'Rachel',
        title: 'Lead People Admin',
        otherInfoOne: 'I like the Mediterranean 🌊',
        otherInfoTwo: 'I love the 7th art 🎬',
        otherInfoThree: 'I speak legalese 📜',
        otherInfoFour: 'I hate tripe 🤮',
        otherInfoFive: '',
    },
    {
        id: 7,
        type: 'engineering',
        img: img8,
        name: 'Lukas',
        title: 'Lead Web Developer',
        otherInfoOne: 'I like machinery 🛠️',
        otherInfoTwo: 'Old motorcycle and VW fan 🚗 🏍️',
        otherInfoThree: 'Senior Ouebmaster 🕸️',
        otherInfoFour: 'I hate breaking down...',
        otherInfoFive: '',
    },
    {
        id: 8,
        type: 'user',
        img: img9,
        name: 'Leah',
        title: 'Brand Content Specialist',
        otherInfoOne: 'I like figure skating 🎿',
        otherInfoTwo: 'Brunch connaisseur 🥞',
        otherInfoThree: 'Bilingual content creator 🗣️',
        otherInfoFour: "I don't like making decisions 🤔",
        otherInfoFive: '',
    },
    {
        id: 9,
        type: 'engineering',
        img: img10,
        name: 'Benjamin',
        title: 'Engineering Manager Backend',
        otherInfoOne: 'I like the mountains 🏔',
        otherInfoTwo: 'I ♥ board games 🎲',
        otherInfoThree: 'I tinker with the production 🛠',
        otherInfoFour: 'I run from uncertainty 🏃',
        otherInfoFive: '',
    },
    {
        id: 10,
        type: 'product',
        img: img11,
        name: 'Morgane',
        title: 'Creative Lead',
        otherInfoOne: "I'm a travel addict 🌍",
        otherInfoTwo: 'CreationS fan 🎨',
        otherInfoThree: 'Multi-task designer 🎨',
        otherInfoFour: 'I hate public speaking 🙈',
        otherInfoFive: '',
    },
    {
        id: 11,
        type: 'engineering',
        img: img12,
        name: 'Julien',
        title: 'Lead Backend Developer',
        otherInfoOne: 'I like team sports 🏀',
        otherInfoTwo: 'I love video games 🎮',
        otherInfoThree: 'Tool and API creator 📡',
        otherInfoFour: "I don't like Haribos 🍬",
        otherInfoFive: '',
    },
    {
        id: 12,
        type: 'finance',
        img: img13,
        name: 'Barbara',
        title: 'Head of Finance',
        otherInfoOne: 'I like to read novels 📚',
        otherInfoTwo: 'I live for Broadway 🎭',
        otherInfoThree: 'I tame the Excel beast 🐉',
        otherInfoFour: 'I detest cigarettes 🚬',
        otherInfoFive: '',
    },
    {
        id: 13,
        type: 'product',
        img: img14,
        name: 'Benoit',
        title: 'Design Manager',
        otherInfoOne: 'I ♥ cinéma and photo 🎬',
        otherInfoTwo: 'Games and guitare fan 🎸',
        otherInfoThree: "I'm the proto master 🤓",
        otherInfoFour: "I hate onions 🧄",
        otherInfoFive: '',
    },
    {
        id: 14,
        type: 'marketing',
        img: img15,
        name: 'Alice',
        title: 'Growth Marketing Manager',
        otherInfoOne: 'I like slow coffee ☕',
        otherInfoTwo: 'I ♥ interior design 🖼️',
        otherInfoThree: 'I spend 💰 on the Big 4',
        otherInfoFour: "I don't like waking up early 🌅",
        otherInfoFive: '',
    },
    {
        id: 15,
        type: 'engineering',
        img: img16,
        name: 'Mikhail',
        title: 'Lead Developer Android',
        otherInfoOne: 'I like hiking 🥾',
        otherInfoTwo: 'I love traveling 🌍',
        otherInfoThree: 'I speak fluent Kotlin 👨‍💻',
        otherInfoFour: "I don't like falling while skiing 🎿",
        otherInfoFive: '',
    },
    {
        id: 16,
        type: 'people',
        img: img17,
        name: 'Marine',
        title: 'People Development Partner',
        otherInfoOne: 'I like to ski 🎿',
        otherInfoTwo: "I'm passionate about dance 🕺",
        otherInfoThree: 'I unearth talent...',
        otherInfoFour: "I don't like fish 🐟",
        otherInfoFive: '',
    },
    {
        id: 17,
        type: 'engineering',
        img: img18,
        name: 'Matteo',
        title: 'iOS Developer',
        otherInfoOne: 'I like Mexican food 🌮',
        otherInfoTwo: '70s music fan 🎶',
        otherInfoThree: 'I push 3D boundaries 🤯',
        otherInfoFour: "I don't like dogs 🐶",
        otherInfoFive: '',
    },
    {
        id: 18,
        type: 'product',
        img: img19,
        name: 'Julia',
        title: 'Product Designer',
        otherInfoOne: 'I like gardening 🌱',
        otherInfoTwo: 'I never get bored 😴',
        otherInfoThree: 'I explore design limits 🤯',
        otherInfoFour: "I don't like the cold 🥶",
        otherInfoFive: '',
    },
    {
        id: 19,
        type: 'engineering',
        img: img20,
        name: 'Gabriel',
        title: 'Android Developer',
        otherInfoOne: 'I like reading and traveling 📚',
        otherInfoTwo: 'I love creative activities 🎨',
        otherInfoThree: 'UI Android conceptor',
        otherInfoFour: "I don't like noise 🚨",
        otherInfoFive: '',
    },
    {
        id: 20,
        type: 'marketing',
        img: img21,
        name: 'Emilie',
        title: 'Brand Project Coordinator',
        otherInfoOne: 'I ♥ sushi with sweet sauce 🍣',
        otherInfoTwo: 'I love hiking & traveling 🌍',
        otherInfoThree: 'Facebook and Insta hold no secrets for me 🤫',
        otherInfoFour: "I don't like lentils 🥫",
        otherInfoFive: '',
    },
    {
        id: 21,
        type: 'finance',
        img: img22,
        name: 'Elodie',
        title: 'Head of People',
        otherInfoOne: 'I ♥ maple syrup 🇨🇦',
        otherInfoTwo: 'I love cactuses 🌵',
        otherInfoThree: 'Communication and listening 🗣',
        otherInfoFour: 'I hate running 🏃',
        otherInfoFive: '',
    },
    {
        id: 22,
        type: 'user',
        img: img23,
        name: 'Elodie',
        title: 'Financial Controller',
        otherInfoOne: 'I ♥ hiking ⛰',
        otherInfoTwo: 'I love handball 🏐',
        otherInfoThree: 'Excel holds no secrets for me 📈',
        otherInfoFour: 'I hate coriander 🌿',
        otherInfoFive: '',
    },
    {
        id: 23,
        type: 'partnership',
        img: img24,
        name: 'Kahina',
        title: 'Partnership Developer',
        otherInfoOne: 'I ♥ good food 🍽',
        otherInfoTwo: 'I like new places 🌍',
        otherInfoThree: 'I am a chameleon 🦎',
        otherInfoFour: 'I hate melon 🍈',
        otherInfoFive: '',
    },
    {
        id: 24,
        type: 'marketing',
        img: img25,
        name: 'Marie',
        title: 'Engineering Manager Data',
        otherInfoOne: 'I ♥ long walks 🚶',
        otherInfoTwo: 'I like trail 🏃',
        otherInfoThree: 'Make discoveries...',
        otherInfoFour: 'I hate loneliness 🙁',
        otherInfoFive: '',
    },

    {
        id: 25,
        type: 'user',
        img: img26,
        name: 'Marine',
        title: 'People Development Partner',
        otherInfoOne: 'I like to ski 🎿',
        otherInfoTwo: "I'm passionate about dance 🕺",
        otherInfoThree: 'I unearth talent...',
        otherInfoFour: "I don't like fish 🐟",
        otherInfoFive: '',
    },
    {
        id: 26,
        type: 'product',
        img: img27,
        name: 'Matteo',
        title: 'iOS Developer',
        otherInfoOne: 'I like Mexican food 🌮',
        otherInfoTwo: '70s music fan 🎶',
        otherInfoThree: 'I push 3D boundaries 🤯',
        otherInfoFour: "I don't like dogs 🐶",
        otherInfoFive: '',
    },
    {
        id: 27,
        type: 'user',
        img: img28,
        name: 'Julia',
        title: 'Product Designer',
        otherInfoOne: 'I like gardening 🌱',
        otherInfoTwo: 'I never get bored 😴',
        otherInfoThree: 'I explore design limits 🤯',
        otherInfoFour: "I don't like the cold 🥶",
        otherInfoFive: '',
    },
    {
        id: 28,
        type: 'product',
        img: img29,
        name: 'Gabriel',
        title: 'Android Developer',
        otherInfoOne: 'I like reading and traveling 📚',
        otherInfoTwo: 'I love creative activities 🎨',
        otherInfoThree: 'UI Android conceptor...',
        otherInfoFour: "I don't like noise 🚨",
        otherInfoFive: '',
    },
    {
        id: 29,
        type: 'user',
        img: img30,
        name: 'Emilie',
        title: 'Brand Project Coordinator',
        otherInfoOne: 'I ♥ sushi with sweet sauce 🍣',
        otherInfoTwo: 'I love hiking & traveling 🌍',
        otherInfoThree: 'Facebook and Insta hold no secrets for me 🤫',
        otherInfoFour: "I don't like lentils 🥫",
        otherInfoFive: '',
    },
    {
        id: 30,
        type: 'product',
        img: img31,
        name: 'Elodie',
        title: 'Head of People',
        otherInfoOne: 'I ♥ maple syrup 🇨🇦',
        otherInfoTwo: 'I love cactuses 🌵',
        otherInfoThree: 'Communication and listening 🗣',
        otherInfoFour: 'I hate running 🏃',
        otherInfoFive: '',
    },
    {
        id: 31,
        type: 'product',
        img: img32,
        name: 'Elodie',
        title: 'Financial Controller',
        otherInfoOne: 'I ♥ hiking ⛰',
        otherInfoTwo: 'I love handball 🏐',
        otherInfoThree: 'Excel holds no secrets for me 📈',
        otherInfoFour: 'I hate coriander 🌿',
        otherInfoFive: '',
    },
    {
        id: 32,
        type: 'user',
        img: img33,
        name: 'Kahina',
        title: 'Partnership Developer',
        otherInfoOne: 'I ♥ good food 🍽',
        otherInfoTwo: 'I like new places 🌍',
        otherInfoThree: 'I am a chameleon 🦎',
        otherInfoFour: "I hate melon 🍈",
        otherInfoFive: '',
    },
    {
        id: 33,
        type: 'engineering',
        img: img34,
        name: 'Marie',
        title: 'Engineering Manager Data',
        otherInfoOne: 'I ♥ long walks 🚶',
        otherInfoTwo: 'I like trail 🏃',
        otherInfoThree: 'Make discoveries...',
        otherInfoFour: "I hate loneliness 🙁",
        otherInfoFive: '',
    },
    {
        id: 34,
        type: 'product',
        img: img35,
        name: 'Mael',
        title: 'User Researcher',
        otherInfoOne: 'I ♥ video games 🎮',
        otherInfoTwo: 'I like music 🎵',
        otherInfoThree: 'Passionate researcher 🧐',
        otherInfoFour: 'I hate waiting ⌛',
        otherInfoFive: '',
    },
    {
        id: 35,
        type: 'engineering',
        img: img36,
        name: 'Maxime',
        title: 'Engineering Manager Mobile',
        otherInfoOne: 'I ♥ cats 🐱',
        otherInfoTwo: 'I like video games 👾',
        otherInfoThree: 'Jack of all trades 👈',
        otherInfoFour: 'I hate mornings ⏰',
        otherInfoFive: '',
    },
    {
        id: 36,
        type: 'engineering',
        img: img37,
        name: 'Elie',
        title: 'Backend Developer',
        otherInfoOne: 'I ♥ sunbath 🇷🇪',
        otherInfoTwo: 'I like biking 🚲',
        otherInfoThree: 'I want to automate everything 😂',
        otherInfoFour: 'I hate not knowing ❌',
        otherInfoFive: '',
    },
    {
        id: 37,
        type: 'product',
        img: img38,
        name: 'Flore',
        title: 'Product Manager',
        otherInfoOne: 'I ♥ traveling 🌍',
        otherInfoTwo: 'I like meeting new people 🤝',
        otherInfoThree: 'I organize and plan 📝',
        otherInfoFour: 'I hate feet 🦶',
        otherInfoFive: '',
    },
    {
        id: 38,
        type: 'engineering',
        img: img39,
        name: 'Kevin',
        title: 'Senior Web Developer',
        otherInfoOne: 'I ♥ countryside 🌍',
        otherInfoTwo: 'I like puzzle 🧩',
        otherInfoThree: 'I format data 📊',
        otherInfoFour: "I hate mushrooms 🍄",
        otherInfoFive: '',
    },
    {
        id: 39,
        type: 'product',
        img: img40,
        name: 'Mathilda',
        title: 'Lead User Researcher',
        otherInfoOne: 'I ♥ baby Yoda 🥹',
        otherInfoTwo: 'I like surf 🏄‍♀️',
        otherInfoThree: 'I ask the right questions 🤔',
        otherInfoFour: "I hate fish 🐟",
        otherInfoFive: '',
    },
    {
        id: 40,
        type: 'product',
        img: img41,
        name: 'Laurie',
        title: 'Graphic Designer 360',
        otherInfoOne: 'I ♥ the smell of books 📚',
        otherInfoTwo: 'I like crafting 🛠',
        otherInfoThree: 'I bring graphics to life 🎨',
        otherInfoFour: "I hate disrespect 🤬",
        otherInfoFive: '',
    },
    {
        id: 41,
        type: 'finance',
        img: img42,
        name: 'Anais',
        title: 'Business Controller',
        otherInfoOne: 'I ♥ travelling 🌍',
        otherInfoTwo: 'I like blind test 🎶',
        otherInfoThree: 'I explore the numbers 📊',
        otherInfoFour: "I hate being bored 😴",
        otherInfoFive: '',
    },
    {
        id: 42,
        type: 'engineering',
        img: img43,
        name: 'Christopher',
        title: 'Senior Backend Developer',
        otherInfoOne: 'I ♥ very spicy food 🌶️',
        otherInfoTwo: 'I like climbing 🧗',
        otherInfoThree: 'I\'m curious by nature 🕵️',
        otherInfoFour: 'I hate hypocrisy 🤐',
        otherInfoFive: '',
    },
    {
        id: 43,
        type: 'people',
        img: img44,
        name: 'Sylvie',
        title: 'Workplace Coordinator',
        otherInfoOne: 'I ♥ cooking and eating 🤤',
        otherInfoTwo: 'I like knitting and crocheting 👵',
        otherInfoThree: 'I am helpful ☀️',
        otherInfoFour: 'I hate the absence of flashing 🚗',
        otherInfoFive: '',
    },
    {
        id: 44,
        type: 'product',
        img: img45,
        name: 'Marie',
        title: 'Brand Manager',
        otherInfoOne: 'I ♥ almond magnums 🍦',
        otherInfoTwo: 'I like swim in lakes 🏖️',
        otherInfoThree: 'I manage multiple projects 🤹‍♀️',
        otherInfoFour: "I hate footbaths 👣",
        otherInfoFive: '',
    },
    {
        id: 45,
        type: 'user',
        img: img46,
        name: 'Cécile',
        title: 'Web Developer',
        otherInfoOne: 'I like cruising on a longboard 🛹',
        otherInfoTwo: 'I love sausage dogs 🌭',
        otherInfoThree: 'I learn everyday 📚',
        otherInfoFour: "I hate Brussels sprouts 🤢",
        otherInfoFive: '',
    },
    {
        id: 46,
        type: 'marketing',
        img: img47,
        name: 'Alan',
        title: 'Lead Exploration',
        otherInfoOne: 'I like sliding sports 🏂',
        otherInfoTwo: 'I love video games 🎮',
        otherInfoThree: 'I\'m bubbling over with ideas 👨‍🔬',
        otherInfoFour: 'I hate the lack of humility 😑',
        otherInfoFive: '',
    },
    {
        id: 47,
        type: 'marketing',
        img: img48,
        name: 'Sybille',
        title: 'Acquisition Specialist',
        otherInfoOne: 'I love karaoke 🎤',
        otherInfoTwo: 'I ♥ craft activities 🎨',
        otherInfoThree: 'I do advertising 📣',
        otherInfoFour: "I don't like conflict 🥊",
        otherInfoFive: '',
    },
    {
        id: 48,
        type: 'engineering',
        img: img49,
        name: 'Quentin',
        title: 'Web Developer',
        otherInfoOne: 'I like sliding sports',
        otherInfoTwo: 'I love video games 🎮',
        otherInfoThree: 'I\'m bubbling over with ideas!',
        otherInfoFour: 'I hate the lack of humility',
        otherInfoFive: '',
    },

]